### ISSUE TITLE
Extra scrollbar (see attachment!)

### ISSUE THREAD

**Issue by 1951FDG** [oleksbard/brackets-bigger-extensions#1]
Nice extension, but there is an extra scrollbar present!

![kkk](https://cloud.githubusercontent.com/assets/220168/4317639/715dece6-3f15-11e4-885e-54e6e59d4175.jpg)

**Comment by oleksbard** [comment]
Thanks! Fix it soon.

**Comment by 1951FDG** [comment]
Thank you!

**Comment by 1951FDG** [comment]
Fixed! Thanks for the quick fix!
