### ISSUE TITLE
Unable to remove extensions with this extension installed

### ISSUE THREAD

**Issue by 1951FDG** [oleksbard/brackets-bigger-extensions#2]
The remove button next to an installed extension scrolls to top, does not perform any actions. Had to remove 'bigger-extensions' to get the remove functionality working again.

**Comment by oleksbard** [comment]
Sorry, can't reproduce that issue.

**Comment by 1951FDG** [comment]
Tried to reproduce but couldn't. Seems as if the updating the extension went wrong or more likely, maybe I forgot to reload Brackets after updating the extension (Is a reload requested when updating this extension?). After reinstalling the extension, I can't reproduce the issue.

**Comment by oleksbard** [comment]
That's a good news!
