### ISSUE TITLE
Unable to remove extensions with this extension installed (#2)

### ISSUE THREAD

**Issue by 1951FDG** [oleksbard/brackets-bigger-extensions#3]
This issue is the same as closed issue: https://github.com/dnbard/brackets-bigger-extensions/issues/2
###### Symptoms
- The remove button next to an installed extension scrolls to top, does not perform any actions.
- The install button next to an yet to be installed extension scrolls to top, does not perform any actions.

I found a pattern, basically every `install` or `remove` button that is beyond the initial scroll area won't work. e.g., if five extensions are initially visible at the top, then scroll down, the sixth (+) extension `install` or `remove` button will scroll to top, instead of the desired behavior.

**Comment by oleksbard** [comment]
Can you reproduce this issue with only this extension installed?
I'm asking this because I can't reproduce this issue again.

**Comment by 1951FDG** [comment]
Same issue with only this extension installed. Using Brackets sprint 43 experimental build 0.43.0-14375 (release 287868769) on OS X.

**Comment by 1951FDG** [comment]
Thanks for the fix !
